[package]
name = "nit-stream"
version = "0.1.0"
authors = ["Andrey Dyldin <and@cesbo.com>"]
build = "src/build.rs"
edition = "2018"

[dependencies]
ini = { path = "../libini" }
mpegts = { path = "../libmpegts" }

[profile.release]
panic = "abort"
opt-level = 3
lto = true
