[package]
name = "nit-stream"
version = "0.1.0"
authors = ["Cesbo Developers Team"]
build = "src/build.rs"
edition = "2018"

[dependencies]
config = { path = "../libconfig" }
udp = { path = "../libudp" }
mpegts = { path = "../libmpegts" }

[profile.release]
panic = "abort"
opt-level = 3
lto = true
